/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/health": {
    /**
     * Migration state
     * @description Answerable throughout a boot, including before migrations have run and after they have failed — that is the whole point of it. It reports what the migration run recorded, so it is not a database liveness check.
     */
    get: {
      responses: {
        /** @description Migrations have applied and kobai is serving. */
        200: {
          content: {
            "application/json": components["schemas"]["Health"];
          };
        };
        /** @description Still starting, or not serving because migrations failed. */
        503: {
          content: {
            "application/json": components["schemas"]["Health"];
          };
        };
      };
    };
  };
  "/admin/session": {
    /**
     * Who the caller is
     * @description What the Admin asks first after a page load: who am I, and what may I do.
     */
    get: {
      responses: {
        /** @description The caller's Merchant and Role. */
        200: {
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Sign in
     * @description The session travels back as an httpOnly `kobai_session` cookie, which a browser then sends on every admin request by itself; it is in no response body. An unknown address and a wrong password are answered identically, and in the same time — distinguishing them would turn this into a way to ask who works here.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SignInRequest"];
        };
      };
      responses: {
        /** @description Who you now are. The credential itself is in the cookie. */
        201: {
          headers: {
            /** @description `kobai_session`, httpOnly, SameSite=Strict, and Secure whenever the request arrived over HTTPS. It names no Path, so a browser scopes it to the admin surface this request reached — `/admin`, or `/api/admin` for a Project that mounted kobai at `/api`. A browser sends it back by itself; nothing else has to. */
            "set-cookie": string;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
        /** @description The request does not fit this endpoint's schema. */
        400: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description Those credentials are not valid. */
        401: {
          content: {
            "application/json": components["schemas"]["InvalidCredentials"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Sign out
     * @description The row goes, so the session stops working on the very next request, and the cookie is cleared so the browser stops sending it. Both halves matter: clearing only the cookie would leave a live session behind, and deleting only the row would leave the browser presenting a credential to be refused.
     */
    delete: {
      responses: {
        /** @description Signed out. */
        204: {
          headers: {
            /** @description `kobai_session`, emptied and expired, so the browser drops it. */
            "set-cookie": string;
          };
          content: never;
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/merchants": {
    /**
     * Create a Merchant
     * @description Adds a colleague. The deployment's *first* Merchant does not come from here — it is seeded at boot from the deployment's own configuration, because a deployment with no Merchant has nobody who could hold this permission.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateMerchantRequest"];
        };
      };
      responses: {
        /** @description The Merchant, and the Role they hold. */
        201: {
          content: {
            "application/json": components["schemas"]["Merchant"];
          };
        };
        /** @description The request does not fit this endpoint's schema. */
        400: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description A Merchant already holds that address. */
        409: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/store": {
    /**
     * Read the Store
     * @description One deployment is one Store (ADR-0005), so this takes no identifier.
     */
    get: {
      responses: {
        /** @description The Store. */
        200: {
          content: {
            "application/json": components["schemas"]["Store"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/products": {
    /**
     * List Products
     * @description Newest first, unpaginated. The envelope is why pagination can arrive beside the list rather than by breaking this response.
     */
    get: {
      responses: {
        /** @description Every Product. */
        200: {
          content: {
            "application/json": components["schemas"]["ProductList"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Create a Product
     * @description A Product and its Variants are created together. There is no route that creates a Product alone, so a Product with no Variant is not a state this API can produce.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateProductRequest"];
        };
      };
      responses: {
        /** @description The Product, with its Variants. */
        201: {
          content: {
            "application/json": components["schemas"]["ProductDetail"];
          };
        };
        /** @description The request does not fit this endpoint's schema. */
        400: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description A Variant already carries one of those SKUs. */
        409: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/products/{id}": {
    /**
     * Read a Product
     * @description One Product, with its Variants and each Variant's Prices.
     */
    get: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description The Product. */
        200: {
          content: {
            "application/json": components["schemas"]["ProductDetail"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Product exists. */
        404: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/variants/{id}/prices": {
    /**
     * Price a Variant
     * @description An insert, never an update. Calling this twice leaves a Variant with two Prices — which is how sale prices, further currencies and quantity breaks arrive without a migration.
     */
    post: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SetPriceRequest"];
        };
      };
      responses: {
        /** @description The Price. */
        201: {
          content: {
            "application/json": components["schemas"]["Price"];
          };
        };
        /** @description The request does not fit this endpoint's schema. */
        400: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Variant exists. */
        404: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description Well formed, and still refused: this Store does not price in that currency. */
        422: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/api-keys": {
    /**
     * List API keys
     * @description Newest first, unpaginated, revoked keys included. It carries no key value and no fragment of one — only a digest is stored, so there is nothing to show a second time.
     */
    get: {
      responses: {
        /** @description Every API key, and whether it still works. */
        200: {
          content: {
            "application/json": components["schemas"]["ApiKeyList"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Mint an API key
     * @description The value is in this response and in no other, ever — only a digest is stored. `kobai_pk_…` is publishable and `kobai_sk_…` is secret, so the kind is readable off the value itself.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateApiKeyRequest"];
        };
      };
      responses: {
        /** @description The key, shown once. */
        201: {
          content: {
            "application/json": components["schemas"]["IssuedApiKey"];
          };
        };
        /** @description The request does not fit this endpoint's schema. */
        400: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/api-keys/{id}": {
    /**
     * Revoke an API key
     * @description It stops working on the very next request, like a deleted Session.
     */
    delete: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description Revoked. */
        204: {
          content: never;
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such API key exists. */
        404: {
          content: {
            "application/json": components["schemas"]["Refusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/store/variants/{id}/price": {
    /**
     * What a Variant costs
     * @description Produced by the `resolve-price` Workflow. The response names the Steps that ran, so a Developer who replaced one can see that theirs did.
     */
    get: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description The resolved Price, and the Steps that produced it. */
        200: {
          content: {
            "application/json": components["schemas"]["ResolvedPrice"];
          };
        };
        /** @description No live API key was presented. */
        401: {
          headers: {
            /** @description The scheme the request failed to satisfy. */
            "www-authenticate": "Bearer";
          };
          content: {
            "application/json": components["schemas"]["ApiKeyRefusal"];
          };
        };
        /** @description A Step refused: there is no such Variant, or it carries no Price. */
        404: {
          content: {
            "application/json": components["schemas"]["PriceRefusal"];
          };
        };
        /** @description A Step this build of Core does not know refused. The request was well formed and the Workflow declined it. */
        422: {
          content: {
            "application/json": components["schemas"]["PriceRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Health: {
      /** @enum {string} */
      status: "ok" | "booting" | "error";
      migrations: components["schemas"]["MigrationState"];
    };
    MigrationState: OneOf<[{
      /** @enum {string} */
      status: "pending";
    }, {
      /** @enum {string} */
      status: "running";
    }, {
      /** @enum {string} */
      status: "applied";
      sets: components["schemas"]["AppliedMigrationSet"][];
    }, {
      /** @enum {string} */
      status: "failed";
      set: string | null;
      message: string;
    }]>;
    AppliedMigrationSet: {
      name: string;
      migrationsTable: string;
      migrationsSchema: string;
      /** @description Rows in this set's tracking table. */
      applied: number;
    };
    Session: {
      /** Format: date-time */
      expiresAt: string;
      merchant: components["schemas"]["MerchantIdentity"];
      role: components["schemas"]["RoleSummary"];
    };
    MerchantIdentity: {
      /** Format: uuid */
      id: string;
      email: string;
    };
    RoleSummary: {
      name: string;
      /** @description What this Role may do. A deployment may hold a permission this build of Core has never heard of. */
      permissions: string[];
    };
    Refusal: {
      /** @description What went wrong, in prose. */
      error: string;
      /** @description Machine-readable. Branch on this. */
      reason: string;
    };
    InvalidCredentials: {
      error: string;
      /** @enum {string} */
      reason: "invalid-credentials";
    };
    ServerError: {
      error: string;
    };
    Unavailable: {
      error: string;
      /** @enum {string} */
      status: "booting" | "error";
      migrations: components["schemas"]["MigrationState"];
    };
    SignInRequest: {
      email: string;
      password: string;
    };
    Merchant: components["schemas"]["MerchantIdentity"] & {
      role: components["schemas"]["RoleSummary"];
    };
    SessionRefusal: {
      error: string;
      /** @enum {string} */
      reason: "session-missing" | "session-malformed" | "session-unknown" | "session-expired";
    };
    PermissionDenied: {
      error: string;
      /** @enum {string} */
      reason: "permission-denied";
      /** @description The permission the Role does not hold. */
      required: string;
    };
    CreateMerchantRequest: {
      email: string;
      password: string;
      /** @description A Role by name. Defaults to `owner`. */
      role?: string;
    };
    Store: {
      name: string;
      /** @description ISO 4217, upper case. */
      defaultCurrency: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
    };
    ProductDetail: components["schemas"]["Product"] & {
      variants: components["schemas"]["Variant"][];
    };
    Variant: {
      /** Format: uuid */
      id: string;
      sku: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
      /** @description Every Price set on this Variant. A Price is a row, so there may be several. */
      prices: components["schemas"]["Price"][];
    };
    Price: {
      /** Format: uuid */
      id: string;
      /** @description Minor units of `currency` — 1250 is USD 12.50. */
      amount: number;
      currency: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
    };
    Product: {
      /** Format: uuid */
      id: string;
      title: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
    };
    CreateProductRequest: {
      title: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata?: {
        [key: string]: unknown;
      };
      variants: components["schemas"]["CreateVariantRequest"][];
    };
    CreateVariantRequest: {
      sku: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    ProductList: {
      products: components["schemas"]["Product"][];
    };
    SetPriceRequest: {
      /** @description Minor units — 1250 for USD 12.50. Whole, and not negative. */
      amount: number;
      /** @description ISO 4217. Defaults to the Store's default currency. */
      currency?: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    IssuedApiKey: {
      /** Format: uuid */
      id: string;
      name: string;
      kind: components["schemas"]["ApiKeyKind"];
      /** Format: date-time */
      createdAt: string;
      /** @description The value itself. Shown at creation and unrecoverable afterwards. */
      key: string;
    };
    /** @enum {string} */
    ApiKeyKind: "publishable" | "secret";
    CreateApiKeyRequest: {
      /** @description How a Merchant tells one key from another when revoking. */
      name: string;
      kind: components["schemas"]["ApiKeyKind"];
    };
    ApiKeyList: {
      apiKeys: components["schemas"]["ApiKeySummary"][];
    };
    ApiKeySummary: {
      /** Format: uuid */
      id: string;
      name: string;
      kind: components["schemas"]["ApiKeyKind"];
      /** Format: date-time */
      createdAt: string;
      /**
       * Format: date-time
       * @description When it stopped working, or `null` while it still does.
       */
      revokedAt: string | null;
    };
    ResolvedPrice: {
      variant: components["schemas"]["VariantIdentity"];
      price: {
        /** Format: uuid */
        id: string;
        amount: number;
        currency: string;
      };
      workflow: {
        name: string;
        steps: components["schemas"]["StepReport"][];
      };
    };
    VariantIdentity: {
      /** Format: uuid */
      id: string;
      sku: string;
    };
    StepReport: {
      /** @description The slot the Workflow declares. */
      step: string;
      /** @description The Step that filled it. Differs when a Project replaced it. */
      implementation: string;
    };
    ApiKeyRefusal: {
      error: string;
      /** @enum {string} */
      reason: "api-key-missing" | "api-key-malformed" | "api-key-unknown" | "api-key-revoked";
    };
    PriceRefusal: {
      error: string;
      reason: string;
      workflow: {
        name: string;
        /** @description The slot that refused. */
        failed: string;
        steps: components["schemas"]["StepReport"][];
      };
    };
  };
  responses: never;
  parameters: {
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
