/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/health": {
    /**
     * Migration state
     * @description Answerable throughout a boot, including before migrations have run and after they have failed — that is the whole point of it. It reports what the migration run recorded, so it is not a database liveness check.
     */
    get: {
      responses: {
        /** @description Migrations have applied and kobai is serving. */
        200: {
          content: {
            "application/json": components["schemas"]["Health"];
          };
        };
        /** @description Still starting, or not serving because migrations failed. */
        503: {
          content: {
            "application/json": components["schemas"]["Health"];
          };
        };
      };
    };
  };
  "/admin/session": {
    /**
     * Who the caller is
     * @description What the Admin asks first after a page load: who am I, and what may I do.
     */
    get: {
      responses: {
        /** @description The caller's Merchant and Role. */
        200: {
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Sign in
     * @description The session travels back as an httpOnly `kobai_session` cookie, which a browser then sends on every admin request by itself; it is in no response body. An unknown address and a wrong password are answered identically, and in the same time — distinguishing them would turn this into a way to ask who works here.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SignInRequest"];
        };
      };
      responses: {
        /** @description Who you now are. The credential itself is in the cookie. */
        201: {
          headers: {
            /** @description `kobai_session`, httpOnly, SameSite=Strict, and Secure whenever the request arrived over HTTPS. It names no Path, so a browser scopes it to the admin surface this request reached — `/admin`, or `/api/admin` for a Project that mounted kobai at `/api`. A browser sends it back by itself; nothing else has to. */
            "set-cookie": string;
          };
          content: {
            "application/json": components["schemas"]["Session"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or is not JSON at all. */
        400: {
          content: {
            "application/json": components["schemas"]["InvalidRequest"];
          };
        };
        /** @description Those credentials are not valid. */
        401: {
          content: {
            "application/json": components["schemas"]["InvalidCredentials"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Sign out
     * @description The row goes, so the session stops working on the very next request, and the cookie is cleared so the browser stops sending it. Both halves matter: clearing only the cookie would leave a live session behind, and deleting only the row would leave the browser presenting a credential to be refused.
     */
    delete: {
      responses: {
        /** @description Signed out. */
        204: {
          headers: {
            /** @description `kobai_session`, emptied and expired, so the browser drops it. */
            "set-cookie": string;
          };
          content: never;
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/merchants": {
    /**
     * Create a Merchant
     * @description Adds a colleague. The deployment's *first* Merchant does not come from here — it is seeded at boot from the deployment's own configuration, because a deployment with no Merchant has nobody who could hold this permission.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateMerchantRequest"];
        };
      };
      responses: {
        /** @description The Merchant, and the Role they hold. */
        201: {
          content: {
            "application/json": components["schemas"]["Merchant"];
          };
        };
        /** @description The request does not fit this endpoint's schema, is not JSON at all, or names a Role this deployment does not have. */
        400: {
          content: {
            "application/json": components["schemas"]["MerchantRefusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description A Merchant already holds that address. */
        409: {
          content: {
            "application/json": components["schemas"]["MerchantRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/store": {
    /**
     * Read the Store
     * @description One deployment is one Store (ADR-0005), so this takes no identifier.
     */
    get: {
      responses: {
        /** @description The Store. */
        200: {
          content: {
            "application/json": components["schemas"]["Store"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Change the Store
     * @description Changes only what is named; a field left out is left alone, and a named `metadata` replaces what is stored rather than merging into it. `defaultCurrency` may be named and may not be moved: the code this Store already prices in is accepted and changes nothing, and any other is refused, because every Price carries the Store's default currency and no other — changing it would reinterpret each amount already stored rather than convert it. A body naming nothing that would change — `{}`, or only the `defaultCurrency` this Store already has — is refused at 400 rather than answered with the record unchanged.
     */
    patch: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateStoreRequest"];
        };
      };
      responses: {
        /** @description The Store, as a read of it reports it. */
        200: {
          content: {
            "application/json": components["schemas"]["Store"];
          };
        };
        /** @description The request does not fit this endpoint's schema, is not JSON at all, or names nothing this route would change. */
        400: {
          content: {
            "application/json": components["schemas"]["StoreRefusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description Well formed, and still refused: `default-currency-is-fixed`, the request names a currency other than the one this Store prices in. */
        422: {
          content: {
            "application/json": components["schemas"]["StoreRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/products": {
    /**
     * List Products
     * @description Newest first, 20 at a time. Ask for more with `limit`, and for what follows a page with the `nextCursor` it answered — `nextCursor` is absent on the last page, and that absence is the only end-of-list signal (ADR-0064).
     */
    get: {
      parameters: {
        query?: {
          /** @description How many to answer with. Between 1 and 100; 20 if it is not sent. More than 100 is **refused** rather than quietly reduced, because a caller that asked for 5,000 and received 100 would read the short page as the end of the list. */
          limit?: number;
          /** @description The `nextCursor` of the previous page. **Opaque** — it is not an identifier, not a timestamp, and nothing about what is inside it is promised. Send it back exactly as it was received; omit it for the first page. */
          after?: string;
        };
      };
      responses: {
        /** @description A page of Products. */
        200: {
          content: {
            "application/json": components["schemas"]["ProductList"];
          };
        };
        /** @description `limit` is not a whole number between 1 and 100, or `after` is not a cursor this API issued. A `limit` above the ceiling is refused rather than reduced to it. */
        400: {
          content: {
            "application/json": components["schemas"]["InvalidRequest"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Create a Product
     * @description A Product and its Variants are created together. There is no route that creates a Product alone, so a Product with no Variant is not a state this API can produce.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateProductRequest"];
        };
      };
      responses: {
        /** @description The Product, with its Variants. */
        201: {
          content: {
            "application/json": components["schemas"]["ProductDetail"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or is not JSON at all. */
        400: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description A Variant already carries one of those SKUs. */
        409: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description A Variant names a Fulfilment Strategy this deployment has not wired. Core ships `physical` and `digital`; a Plugin's is wired in the Project's `kobai.config.ts`, and installing the Plugin does not wire it. */
        422: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/products/{id}": {
    /**
     * Read a Product
     * @description One Product, with its Variants and each Variant's Prices.
     */
    get: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description The Product. */
        200: {
          content: {
            "application/json": components["schemas"]["ProductDetail"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Product exists. */
        404: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Delete a Product
     * @description Every Variant of it goes too, with their Prices and stock counts — this is also how a Product's last Variant is deleted, since a Variant that is a Product's only one cannot be deleted on its own (ADR-0008). Orders already placed are untouched: their Line Items are a snapshot (ADR-0009).
     */
    delete: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description Deleted. */
        204: {
          content: never;
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Product exists. */
        404: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description `stock-is-reserved`: one of this Product's Variants has stock currently claimed by Reservations being placed. Those either become Orders or lapse, and it can be deleted once they have. */
        409: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Correct a Product
     * @description Changes only what is named; a field left out is left alone, and a named `metadata` replaces what is stored rather than merging into it. The title is free to move — an Order's Line Items are a snapshot, so nothing already sold is rewritten (ADR-0009). Variants are not changed here: add one with `POST /admin/products/{id}/variants`, correct one with `PATCH /admin/variants/{id}`.
     */
    patch: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateProductRequest"];
        };
      };
      responses: {
        /** @description The Product, with its Variants. */
        200: {
          content: {
            "application/json": components["schemas"]["ProductDetail"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or is not JSON at all. */
        400: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Product exists. */
        404: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/products/{id}/variants": {
    /**
     * Add a Variant
     * @description A second size, colour or format for a Product a Merchant already has. It answers with the new Variant, which starts with no Price and no stock count — `POST /admin/variants/{id}/prices` sets the first, and `PUT /admin/variants/{id}/inventory` counts it. Every Variant already on the Product is untouched, which is the point: recreating the Product to add one would discard their Prices and their counts.
     */
    post: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateVariantRequest"];
        };
      };
      responses: {
        /** @description The Variant, as a read of its Product reports it. */
        201: {
          content: {
            "application/json": components["schemas"]["Variant"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or is not JSON at all. */
        400: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Product exists. */
        404: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description `sku-taken`: a Variant already carries that SKU, and a SKU identifies one Variant. */
        409: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Well formed, and still refused: this deployment has not wired a Fulfilment Strategy of that name. Core ships `physical` and `digital`; a Plugin's is wired in the Project's `kobai.config.ts`, and installing the Plugin does not wire it. */
        422: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/variants/{id}": {
    /**
     * Delete a Variant
     * @description Its Prices, its stock count and any Cart line that selected it go with it. Orders do not: an Order's Line Items are a snapshot, so deleting the Variant they were placed for leaves them saying exactly what was bought and what it cost (ADR-0009).
     */
    delete: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description Deleted. */
        204: {
          content: never;
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Variant exists. */
        404: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Two reasons: `last-variant`, this is the only Variant of its Product and every Product has at least one (ADR-0008) — delete the Product instead, which takes this Variant with it; or `stock-is-reserved`, its stock is currently claimed by Reservations being placed, which either become Orders or lapse. */
        409: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Correct a Variant
     * @description Changes only what is named; a field left out is left alone. The SKU and the Fulfilment Strategy are both free to move — an Order's Line Items are a snapshot, so nothing already sold is rewritten (ADR-0009) — and a stock count taken for this Variant is left exactly as it is whichever Strategy it now points at. A Price is not set here: `POST /admin/variants/{id}/prices` adds one, which supersedes.
     */
    patch: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateVariantRequest"];
        };
      };
      responses: {
        /** @description The Variant, as a read of its Product reports it. */
        200: {
          content: {
            "application/json": components["schemas"]["Variant"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or is not JSON at all. */
        400: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Variant exists. */
        404: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description `sku-taken`: another Variant already carries that SKU, and a SKU identifies one Variant. */
        409: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Well formed, and still refused: this deployment has not wired a Fulfilment Strategy of that name. Core ships `physical` and `digital`; a Plugin's is wired in the Project's `kobai.config.ts`, and installing the Plugin does not wire it. */
        422: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/variants/{id}/prices": {
    /**
     * Price a Variant
     * @description An insert, never an update. Calling this twice leaves a Variant with two Prices — which is how sale prices, further currencies and quantity breaks arrive without a migration.
     */
    post: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SetPriceRequest"];
        };
      };
      responses: {
        /** @description The Price. */
        201: {
          content: {
            "application/json": components["schemas"]["Price"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or is not JSON at all. */
        400: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Variant exists. */
        404: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Well formed, and still refused: this Store does not price in that currency. */
        422: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/variants/{id}/prices/{priceId}": {
    /**
     * Remove a Price
     * @description Removing the last one is allowed and leaves the Variant unpriced, which is how a Merchant stops something being sold at once — an unpriced Variant cannot be quoted and cannot be put in a Cart. Orders already placed are unaffected: what was charged is on the Order (ADR-0009).
     */
    delete: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
          /** @description A Price of this Variant. Anything else is not found. */
          priceId: string;
        };
      };
      responses: {
        /** @description Removed. */
        204: {
          content: never;
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Variant exists, or it carries no such Price. */
        404: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/variants/{id}/inventory": {
    /**
     * Count a Variant's stock
     * @description A statement of what the Store has, replacing whatever was there — not an adjustment to it. The first call is what makes a Variant tracked; an untracked Variant sells freely, which is not the same as one counted at zero. `reserved` is never set here: it belongs to the Reservations currently being placed. Read it back with the Product.
     */
    put: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SetInventoryRequest"];
        };
      };
      responses: {
        /** @description What the Store now has of this Variant. */
        200: {
          content: {
            "application/json": components["schemas"]["Inventory"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or is not JSON at all. */
        400: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Variant exists. */
        404: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description More than that is currently claimed by Reservations being placed. Those either become Orders or lapse, and the count can be set once they have. */
        409: {
          content: {
            "application/json": components["schemas"]["CatalogRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/orders": {
    /**
     * List Orders
     * @description Newest first, 20 at a time, and without Line Items — open one for those. Follow `nextCursor` for the next page: this is the list that takes an insert from every Order a storefront places, and a cursor is what makes paging it during a busy hour show each Order exactly once (ADR-0064).
     */
    get: {
      parameters: {
        query?: {
          /** @description How many to answer with. Between 1 and 100; 20 if it is not sent. More than 100 is **refused** rather than quietly reduced, because a caller that asked for 5,000 and received 100 would read the short page as the end of the list. */
          limit?: number;
          /** @description The `nextCursor` of the previous page. **Opaque** — it is not an identifier, not a timestamp, and nothing about what is inside it is promised. Send it back exactly as it was received; omit it for the first page. */
          after?: string;
        };
      };
      responses: {
        /** @description A page of the Orders this Store has taken. */
        200: {
          content: {
            "application/json": components["schemas"]["OrderList"];
          };
        };
        /** @description `limit` is not a whole number between 1 and 100, or `after` is not a cursor this API issued. A `limit` above the ceiling is refused rather than reduced to it. */
        400: {
          content: {
            "application/json": components["schemas"]["InvalidRequest"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/orders/{id}": {
    /**
     * Read an Order
     * @description Its Line Items as they were snapshotted at Capture, its Adjustments, its totals, its Order number and the Payment recorded against it. Nothing here is joined to the catalog, so renaming a Product does not rewrite it (ADR-0009).
     */
    get: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description The Order. */
        200: {
          content: {
            "application/json": components["schemas"]["Order"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such Order exists. */
        404: {
          content: {
            "application/json": components["schemas"]["OrderRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/api-keys": {
    /**
     * List API keys
     * @description Newest first, 20 at a time, revoked keys included. It carries no key value and no fragment of one — only a digest is stored, so there is nothing to show a second time. Pages exactly as the other lists do (ADR-0064).
     */
    get: {
      parameters: {
        query?: {
          /** @description How many to answer with. Between 1 and 100; 20 if it is not sent. More than 100 is **refused** rather than quietly reduced, because a caller that asked for 5,000 and received 100 would read the short page as the end of the list. */
          limit?: number;
          /** @description The `nextCursor` of the previous page. **Opaque** — it is not an identifier, not a timestamp, and nothing about what is inside it is promised. Send it back exactly as it was received; omit it for the first page. */
          after?: string;
        };
      };
      responses: {
        /** @description A page of API keys, and whether each still works. */
        200: {
          content: {
            "application/json": components["schemas"]["ApiKeyList"];
          };
        };
        /** @description `limit` is not a whole number between 1 and 100, or `after` is not a cursor this API issued. A `limit` above the ceiling is refused rather than reduced to it. */
        400: {
          content: {
            "application/json": components["schemas"]["InvalidRequest"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Mint an API key
     * @description The value is in this response and in no other, ever — only a digest is stored. `kobai_pk_…` is publishable and `kobai_sk_…` is secret, so the kind is readable off the value itself.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateApiKeyRequest"];
        };
      };
      responses: {
        /** @description The key, shown once. */
        201: {
          content: {
            "application/json": components["schemas"]["IssuedApiKey"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or is not JSON at all. */
        400: {
          content: {
            "application/json": components["schemas"]["InvalidRequest"];
          };
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/admin/api-keys/{id}": {
    /**
     * Revoke an API key
     * @description It stops working on the very next request, like a deleted Session.
     */
    delete: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description Revoked. */
        204: {
          content: never;
        };
        /** @description No live Merchant session was presented — the `kobai_session` cookie was absent, unusable, unknown or expired. */
        401: {
          content: {
            "application/json": components["schemas"]["SessionRefusal"];
          };
        };
        /** @description The Merchant's Role does not hold the permission this route requires. */
        403: {
          content: {
            "application/json": components["schemas"]["PermissionDenied"];
          };
        };
        /** @description No such API key exists. */
        404: {
          content: {
            "application/json": components["schemas"]["ApiKeyNotFound"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/store/variants/{id}/price": {
    /**
     * What a Variant costs
     * @description Produced by the `resolve-price` Workflow. The response names the Steps that ran, so a Developer who replaced one can see that theirs did.
     */
    get: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description The resolved Price, and the Steps that produced it. */
        200: {
          content: {
            "application/json": components["schemas"]["ResolvedPrice"];
          };
        };
        /** @description No live API key was presented. */
        401: {
          headers: {
            /** @description The scheme the request failed to satisfy. */
            "www-authenticate": "Bearer";
          };
          content: {
            "application/json": components["schemas"]["ApiKeyRefusal"];
          };
        };
        /** @description A Step refused: there is no such Variant, or it carries no Price. */
        404: {
          content: {
            "application/json": components["schemas"]["PriceRefusal"];
          };
        };
        /** @description A Step this build of Core does not know refused. The request was well formed and the Workflow declined it. */
        422: {
          content: {
            "application/json": components["schemas"]["PriceRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/store/carts": {
    /**
     * Start a Cart
     * @description Works for a guest, because Core assumes an authenticated Shopper nowhere (ADR-0020). The `id` in the answer is the whole of the authority to act on this Cart — treat it as a credential. A Shopper may be attached here, but only over a secret key.
     */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateCartRequest"];
        };
      };
      responses: {
        /** @description The Cart, with its Line Items. */
        201: {
          content: {
            "application/json": components["schemas"]["Cart"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or names a value it cannot use. */
        400: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description No live API key was presented. */
        401: {
          headers: {
            /** @description The scheme the request failed to satisfy. */
            "www-authenticate": "Bearer";
          };
          content: {
            "application/json": components["schemas"]["ApiKeyRefusal"];
          };
        };
        /** @description This request asserts who the Shopper is, which needs a secret key (ADR-0020). Detaching one — `"shopper": null` — asserts nothing and does not. */
        403: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/store/carts/{id}": {
    /**
     * Read a Cart
     * @description An expired Cart reads like any other, with `expired` true — so a storefront can say what happened rather than showing nothing, and its Line Items are still there for an abandoned-cart Plugin to find (ADR-0028).
     */
    get: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description The Cart, with its Line Items. */
        200: {
          content: {
            "application/json": components["schemas"]["Cart"];
          };
        };
        /** @description No live API key was presented. */
        401: {
          headers: {
            /** @description The scheme the request failed to satisfy. */
            "www-authenticate": "Bearer";
          };
          content: {
            "application/json": components["schemas"]["ApiKeyRefusal"];
          };
        };
        /** @description No such Cart exists. */
        404: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Attach a Shopper, or change a Cart's own data
     * @description What a storefront calls when a guest signs in half way through. `shopper` needs a secret key; `null` makes the Cart a guest's again.
     */
    patch: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateCartRequest"];
        };
      };
      responses: {
        /** @description The Cart, with its Line Items. */
        200: {
          content: {
            "application/json": components["schemas"]["Cart"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or names a value it cannot use. */
        400: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description No live API key was presented. */
        401: {
          headers: {
            /** @description The scheme the request failed to satisfy. */
            "www-authenticate": "Bearer";
          };
          content: {
            "application/json": components["schemas"]["ApiKeyRefusal"];
          };
        };
        /** @description This request asserts who the Shopper is, which needs a secret key (ADR-0020). Detaching one — `"shopper": null` — asserts nothing and does not. */
        403: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description No such Cart exists. */
        404: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description This Cart can no longer be changed: it has expired, or it has already been placed. It still reads either way. */
        409: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/store/carts/{id}/line-items": {
    /**
     * Add a Variant to a Cart
     * @description Adding a Variant the Cart already carries raises that Line Item's quantity rather than writing a second line. A Variant with no Price is refused: a Store cannot sell what it has not priced.
     */
    post: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddCartLineItemRequest"];
        };
      };
      responses: {
        /** @description The Cart, with its Line Items. */
        200: {
          content: {
            "application/json": components["schemas"]["Cart"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or names a value it cannot use. */
        400: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description No live API key was presented. */
        401: {
          headers: {
            /** @description The scheme the request failed to satisfy. */
            "www-authenticate": "Bearer";
          };
          content: {
            "application/json": components["schemas"]["ApiKeyRefusal"];
          };
        };
        /** @description No such Cart exists, or no such Variant does. */
        404: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description This Cart can no longer be changed: it has expired, or it has already been placed. It still reads either way. */
        409: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description Well formed, and still refused: that Variant carries no Price. */
        422: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/store/carts/{id}/line-items/{lineItemId}": {
    /**
     * Remove a Line Item
     * @description Answers with what is left, so a storefront re-renders the Cart without a second request.
     */
    delete: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
          /** @description A Line Item of this Cart. Anything else is not found. */
          lineItemId: string;
        };
      };
      responses: {
        /** @description The Cart, with its Line Items. */
        200: {
          content: {
            "application/json": components["schemas"]["Cart"];
          };
        };
        /** @description No live API key was presented. */
        401: {
          headers: {
            /** @description The scheme the request failed to satisfy. */
            "www-authenticate": "Bearer";
          };
          content: {
            "application/json": components["schemas"]["ApiKeyRefusal"];
          };
        };
        /** @description No such Cart exists, or this Cart carries no such Line Item. */
        404: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description This Cart can no longer be changed: it has expired, or it has already been placed. It still reads either way. */
        409: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
    /**
     * Change a Line Item
     * @description Its quantity, its own data, or both. A quantity of zero is refused rather than treated as a removal — removing a line is `DELETE`.
     */
    patch: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
          /** @description A Line Item of this Cart. Anything else is not found. */
          lineItemId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateCartLineItemRequest"];
        };
      };
      responses: {
        /** @description The Cart, with its Line Items. */
        200: {
          content: {
            "application/json": components["schemas"]["Cart"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or names a value it cannot use. */
        400: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description No live API key was presented. */
        401: {
          headers: {
            /** @description The scheme the request failed to satisfy. */
            "www-authenticate": "Bearer";
          };
          content: {
            "application/json": components["schemas"]["ApiKeyRefusal"];
          };
        };
        /** @description No such Cart exists, or this Cart carries no such Line Item. */
        404: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description This Cart can no longer be changed: it has expired, or it has already been placed. It still reads either way. */
        409: {
          content: {
            "application/json": components["schemas"]["CartRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/store/orders": {
    /**
     * Turn a Cart into an Order
     * @description Requires a **secret** key: this is where money and stock move, and a publishable key is shipped to a browser (ADR-0055). Prices are resolved now rather than read off the Cart, through the same `resolve-price` Workflow a storefront quotes with — so a Project that replaced a pricing Step charges its own prices here without wiring anything twice. The Order's Line Items hold a snapshot, so the catalog stays freely editable afterwards. Send an `Idempotency-Key` so that retrying after a timeout answers with the Order already placed rather than placing a second one; a Cart becomes exactly one Order either way.
     */
    post: {
      parameters: {
        header?: {
          /** @description A value of your own choosing, unique to this purchase. Send the same one on every retry of the same request and at most one Order is placed; the retry answers 200 with that Order instead of 201. Reusing one for a different body is refused. Optional, and a request without one is not protected against a retry after a timeout. */
          "idempotency-key"?: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PlaceOrderRequest"];
        };
      };
      responses: {
        /** @description This idempotency key has already placed an Order, and this is that Order — nothing was placed again. There is no `workflow` here, because which Steps ran is a fact about the request that placed it. */
        200: {
          content: {
            "application/json": components["schemas"]["Order"];
          };
        };
        /** @description The Order, and the Steps that produced it. */
        201: {
          content: {
            "application/json": components["schemas"]["PlacedOrder"];
          };
        };
        /** @description The request does not fit this endpoint's schema, or a key arrived in both the query string and `metadata`. */
        400: {
          content: {
            "application/json": components["schemas"]["PlaceOrderRequestRefusal"];
          };
        };
        /** @description No live API key was presented. */
        401: {
          headers: {
            /** @description The scheme the request failed to satisfy. */
            "www-authenticate": "Bearer";
          };
          content: {
            "application/json": components["schemas"]["ApiKeyRefusal"];
          };
        };
        /** @description The Payment Provider declined. No Order exists — money is taken before Capture precisely so that a refused card leaves nothing in the Merchant's books — and `error` carries whatever the provider said for itself. */
        402: {
          content: {
            "application/json": components["schemas"]["PlaceOrderRefusal"];
          };
        };
        /** @description The API key is live and publishable, and this route requires a secret one. */
        403: {
          content: {
            "application/json": components["schemas"]["SecretKeyRequired"];
          };
        };
        /** @description A Step refused: there is no such Cart. */
        404: {
          content: {
            "application/json": components["schemas"]["PlaceOrderRefusal"];
          };
        };
        /** @description Nothing was placed, and this request is not the way to place it. Either the Cart can no longer produce an Order — it has expired, or it has already been placed, and a Cart becomes exactly one Order — or the Store has not got enough of something in it left to sell, or this deployment has no Payment Provider configured, or something in the Cart names a Fulfilment Strategy this deployment no longer has wired, or the idempotency key names a different request, or one still in flight. */
        409: {
          content: {
            "application/json": components["schemas"]["PlaceOrderRefusal"];
          };
        };
        /** @description A Step refused. The request was well formed and the Workflow declined it — the Cart is empty, a line can no longer be priced, or a Step this build of Core does not know said no. */
        422: {
          content: {
            "application/json": components["schemas"]["PlaceOrderRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
  "/store/orders/{id}": {
    /**
     * Read an Order
     * @description So reloading a confirmation page needs no client-side cache. A secret key, like placing one: an Order names a Shopper and what they paid, which is not a browser's to read back (ADR-0055).
     */
    get: {
      parameters: {
        path: {
          /** @description An identifier. Anything that is not one is not found. */
          id: string;
        };
      };
      responses: {
        /** @description The Order, exactly as Capture reported it. */
        200: {
          content: {
            "application/json": components["schemas"]["Order"];
          };
        };
        /** @description No live API key was presented. */
        401: {
          headers: {
            /** @description The scheme the request failed to satisfy. */
            "www-authenticate": "Bearer";
          };
          content: {
            "application/json": components["schemas"]["ApiKeyRefusal"];
          };
        };
        /** @description The API key is live and publishable, and this route requires a secret one. */
        403: {
          content: {
            "application/json": components["schemas"]["SecretKeyRequired"];
          };
        };
        /** @description No such Order exists. */
        404: {
          content: {
            "application/json": components["schemas"]["OrderRefusal"];
          };
        };
        /** @description Something failed inside kobai. */
        500: {
          content: {
            "application/json": components["schemas"]["ServerError"];
          };
        };
        /** @description Migrations have not applied, so nothing but `/health` is served yet. */
        503: {
          content: {
            "application/json": components["schemas"]["Unavailable"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Health: {
      /** @enum {string} */
      status: "ok" | "booting" | "error";
      migrations: components["schemas"]["MigrationState"];
    };
    MigrationState: OneOf<[{
      /** @enum {string} */
      status: "pending";
    }, {
      /** @enum {string} */
      status: "running";
    }, {
      /** @enum {string} */
      status: "applied";
      sets: components["schemas"]["AppliedMigrationSet"][];
    }, {
      /** @enum {string} */
      status: "failed";
      set: string | null;
      message: string;
    }]>;
    AppliedMigrationSet: {
      name: string;
      migrationsTable: string;
      migrationsSchema: string;
      /** @description Rows in this set's tracking table. */
      applied: number;
    };
    Session: {
      /**
       * Format: date-time
       * @description When this session ends if no further request is made. Every authenticated request pushes it out by another 30 minutes of idleness, so read it from the most recent response rather than caching the one sign-in returned. It is never later than 12 hours after sign-in, however active the session is; past that the Merchant signs in again.
       */
      expiresAt: string;
      merchant: components["schemas"]["MerchantIdentity"];
      role: components["schemas"]["RoleSummary"];
    };
    MerchantIdentity: {
      /** Format: uuid */
      id: string;
      email: string;
    };
    RoleSummary: {
      name: string;
      /** @description What this Role may do. A deployment may hold a permission this build of Core has never heard of. */
      permissions: string[];
    };
    InvalidRequest: {
      /** @description What went wrong, in prose. */
      error: string;
      /**
       * @description `invalid` if the body does not fit this endpoint's schema; `malformed-body` if it is not JSON at all. Different fixes, so they are different words.
       * @enum {string}
       */
      reason: "invalid" | "malformed-body";
    };
    InvalidCredentials: {
      error: string;
      /** @enum {string} */
      reason: "invalid-credentials";
    };
    ServerError: {
      error: string;
    };
    Unavailable: {
      error: string;
      /** @enum {string} */
      status: "booting" | "error";
      migrations: components["schemas"]["MigrationState"];
    };
    SignInRequest: {
      email: string;
      password: string;
    };
    Merchant: components["schemas"]["MerchantIdentity"] & {
      role: components["schemas"]["RoleSummary"];
    };
    MerchantRefusal: {
      /** @description What went wrong, in prose. */
      error: string;
      /**
       * @description Machine-readable. Branch on this.
       * @enum {string}
       */
      reason: "invalid" | "malformed-body" | "unknown-role" | "email-taken";
    };
    SessionRefusal: {
      error: string;
      /** @enum {string} */
      reason: "session-missing" | "session-malformed" | "session-unknown" | "session-expired";
    };
    PermissionDenied: {
      error: string;
      /** @enum {string} */
      reason: "permission-denied";
      /** @description The permission the Role does not hold. */
      required: string;
    };
    CreateMerchantRequest: {
      email: string;
      password: string;
      /** @description A Role by name. Defaults to `owner`. */
      role?: string;
    };
    Store: {
      name: string;
      /** @description ISO 4217, upper case. */
      defaultCurrency: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
    };
    StoreRefusal: {
      /** @description What went wrong, in prose. */
      error: string;
      /**
       * @description Machine-readable. Branch on this.
       * @enum {string}
       */
      reason: "invalid" | "malformed-body" | "default-currency-is-fixed";
    };
    UpdateStoreRequest: {
      /** @description What this Store is called. Free to change; nothing is keyed by it. */
      name?: string;
      /** @description ISO 4217, read case-insensitively. **Only the code this Store already prices in is accepted**, and naming it changes nothing: every Price carries the Store's default currency and no other (ADR-0008), so changing this would reinterpret every amount already stored rather than convert it. Another currency is refused with `default-currency-is-fixed`. Because naming the current one changes nothing, a body naming *only* this field is refused as a request that changes nothing — send it beside a `name` or a `metadata`. */
      defaultCurrency?: string;
      /** @description Replaces what is stored rather than merging into it. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    ProductDetail: components["schemas"]["Product"] & {
      variants: components["schemas"]["Variant"][];
    };
    Variant: {
      /** Format: uuid */
      id: string;
      sku: string;
      fulfilment: components["schemas"]["VariantFulfilment"];
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
      /** @description Every Price set on this Variant. A Price is a row, so there may be several. */
      prices: components["schemas"]["Price"][];
      inventory: components["schemas"]["Inventory"];
    };
    VariantFulfilment: {
      /** @description The Fulfilment Strategy this Variant is delivered by, by name — `physical`, `digital`, or whatever this deployment wired. What that Strategy answers about shipping, stock and Lead Time is recorded on an Order's Fulfilments, where it is a snapshot rather than a live decision. */
      strategy: string;
    };
    Price: {
      /** Format: uuid */
      id: string;
      /** @description Minor units of `currency` — 1250 is USD 12.50. */
      amount: number;
      currency: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
    };
    /** @description What the Store has of this Variant, or `null` when nobody is counting it. Untracked is not the same as none left: an untracked Variant sells freely. */
    Inventory: {
      /** Format: uuid */
      variantId: string;
      /** @description What the Store physically has. */
      onHand: number;
      /** @description How much of it is claimed by Reservations still being placed. */
      reserved: number;
      /** @description `onHand - reserved` — what is left to sell. */
      available: number;
    } | null;
    Product: {
      /** Format: uuid */
      id: string;
      title: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
    };
    CatalogRefusal: {
      /** @description What went wrong, in prose. */
      error: string;
      /**
       * @description Machine-readable. Branch on this.
       * @enum {string}
       */
      reason: "invalid" | "malformed-body" | "product-not-found" | "variant-not-found" | "price-not-found" | "sku-taken" | "last-variant" | "stock-is-reserved" | "unsupported-currency" | "unknown-fulfilment-strategy";
    };
    CreateProductRequest: {
      title: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata?: {
        [key: string]: unknown;
      };
      variants: components["schemas"]["CreateVariantRequest"][];
    };
    CreateVariantRequest: {
      sku: string;
      fulfilment?: components["schemas"]["VariantFulfilment"];
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    ProductList: {
      products: components["schemas"]["Product"][];
      /** @description Pass as `after` to fetch what follows this page. **Absent when there is no further page**, which is the only way to know the list has ended — a short page is not one. */
      nextCursor?: string;
    };
    UpdateProductRequest: {
      /** @description A new title for this Product. Free to change: an Order's Line Items snapshot the title they were bought under (ADR-0009), so nothing already sold is rewritten. Two Products may share a title — it is what a Product is called, not what identifies it. */
      title?: string;
      /** @description Replaces what is stored rather than merging into it. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    UpdateVariantRequest: {
      /** @description A new SKU for this Variant. Free to change: an Order's Line Items snapshot the SKU they were bought under (ADR-0009), and a Reservation names its subject by identifier rather than by SKU. One another Variant already carries is refused. */
      sku?: string;
      fulfilment?: components["schemas"]["VariantFulfilment"];
      /** @description Replaces what is stored rather than merging into it. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    SetPriceRequest: {
      /** @description Minor units — 1250 for USD 12.50. Whole, and not negative. */
      amount: number;
      /** @description ISO 4217. Defaults to the Store's default currency. */
      currency?: string;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    SetInventoryRequest: {
      /** @description What the Store has, counted. Replaces whatever was there; it is not added to it. */
      onHand: number;
    };
    OrderList: {
      orders: components["schemas"]["OrderSummary"][];
      /** @description Pass as `after` to fetch what follows this page. **Absent when there is no further page**, which is the only way to know the list has ended — a short page is not one. */
      nextCursor?: string;
    };
    OrderSummary: {
      /** Format: uuid */
      id: string;
      /** @description The Order number — what a Shopper reads over the phone, and not the identifier. Monotonic and stable forever, and **not gapless**: gapless numbering is an invoicing requirement, and invoicing is not kobai's. */
      number: number;
      shopper: components["schemas"]["CartShopper"];
      /** @description ISO 4217. Every amount here is in it. */
      currency: string;
      /** @description What was charged, in minor units — every Line Item's total, plus the Order's own Adjustments and the tax on each of them. */
      total: number;
      payment: components["schemas"]["Payment"];
      /**
       * Format: date-time
       * @description The moment of Capture, when this Order became immutable.
       */
      createdAt: string;
    };
    /** @description As at Capture. `null` for a guest, which is the ordinary path. */
    CartShopper: ({
      /** @description The reference's key, as the storefront wrote it. */
      email: string;
      /** @description This Shopper in whatever system the storefront authenticates against. */
      externalId: string | null;
    }) | null;
    /** @description The money taken for this Order. Present on every Order this version of kobai placed — payment is taken before Capture and written in the same transaction, so a declined one leaves no Order at all. `null` is what an Order placed before the Payment record existed reads as. Whether that money actually arrived is `payment.received`, which is a different question and the one a Merchant asks. */
    Payment: {
      /** Format: uuid */
      id: string;
      /** @description What took the money, as the deployment named it — `manual`, `stripe`. An Order placed before the deployment changed provider still says which system holds its money. */
      provider: string;
      /** @description The provider's own handle on this payment. Opaque to kobai, and what a refund is asked against. */
      reference: string;
      /** @description What was taken, in minor units of `currency` — the Order's total. */
      amount: number;
      /** @description ISO 4217. */
      currency: string;
      /** @description Whether the money **arrived**, or was only arranged for. `true` is a card charged or a transfer taken; `false` is a provider that arranges payment out of band — an invoice, a bank transfer, cash at the counter — so the Order is real and nobody has been paid yet. It is what the provider said at Capture and is never updated afterwards: an Order is immutable, and collecting an arranged payment happens outside kobai. */
      received: boolean;
      /** Format: date-time */
      createdAt: string;
    } | null;
    Order: components["schemas"]["OrderSummary"] & {
      /** @description In SKU order, the way a Product reports its Variants — not the order they were added to the Cart. Read a line by its `sku` rather than by position. */
      lineItems: components["schemas"]["OrderLineItem"][];
      /** @description The Adjustments on the Order as a whole — the ones belonging to no single line, such as a basket-wide voucher or a delivery surcharge. A line's own are on the line. These are the ones that carry a `tax` of their own, because there is no Line Item whose tax could carry it. */
      adjustments: components["schemas"]["OrderLevelAdjustment"][];
      /** @description How this Order gets to the Shopper — one per way, on independent timelines, because a mixed Order ships a poster and emails a PDF. Empty for an Order placed before Fulfilment existed. */
      fulfilments: components["schemas"]["Fulfilment"][];
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
    };
    OrderLineItem: {
      /** Format: uuid */
      id: string;
      /**
       * Format: uuid
       * @description The Variant this line was for, for navigation only. `null` once it has been deleted — everything a person reads is beside it.
       */
      variantId: string | null;
      /** @description The Product's title as at Capture. */
      title: string;
      /** @description The Variant's SKU as at Capture. */
      sku: string;
      /** @description What one of it cost, in minor units — 1250 is USD 12.50. */
      unitAmount: number;
      quantity: number;
      /** @description Tax on this line, in minor units. Zero until a tax Step is wired; present so that adding tax later is not a change to what an Order means. */
      tax: number;
      /** @description The discounts and surcharges on this line, in the order they were applied. `unitAmount` above is untouched by them; `total` below accounts for all of them. */
      adjustments: components["schemas"]["OrderAdjustment"][];
      /** @description What this line came to: `unitAmount` × `quantity`, plus its Adjustments, plus `tax`. */
      total: number;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
    };
    OrderAdjustment: {
      /** Format: uuid */
      id: string;
      /** @description Machine-readable, and chosen by the Step that added it — `lead-time-surcharge`, `loyalty-discount`. Core defines none of its own, so this is not a closed set. */
      code: string;
      /** @description For a person to read. */
      description: string;
      /** @description **Signed** minor units: negative discounts, positive surcharges. The total accounts for it either way. */
      amount: number;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
    };
    OrderLevelAdjustment: components["schemas"]["OrderAdjustment"] & {
      /** @description Tax on this Adjustment, in minor units, signed with `amount`. Zero until a tax Step is wired. A line's own Adjustments carry no such figure: a line is taxed after they are applied, so their tax is inside the line's `tax`. */
      tax: number;
    };
    Fulfilment: {
      /** Format: uuid */
      id: string;
      /** @description The Fulfilment Strategy that produced this, by the name the deployment wired it under. Not a closed set: `physical` and `digital` are Core's, and a Plugin's is whatever the Project called it. */
      strategy: string;
      /** @description Whether this part goes anywhere physical, as at Capture. */
      requiresShipping: boolean;
      /** @description Whether selling this took something off a shelf, as at Capture. `false` is why a digital line holds no Reservation. */
      tracksInventory: boolean;
      /** @description Whether there is an interval between Capture and delivery. `true` is a made-to-order line; how long is the Plugin's to know, and reaches the Order as an Adjustment. */
      hasLeadTime: boolean;
      /** @description The Line Items this Fulfilment covers, in the SKU order the Order reports its lines in. Every line of an Order kobai placed is in exactly one. */
      lineItemIds: string[];
    };
    OrderRefusal: {
      error: string;
      /** @enum {string} */
      reason: "order-not-found";
    };
    IssuedApiKey: {
      /** Format: uuid */
      id: string;
      name: string;
      kind: components["schemas"]["ApiKeyKind"];
      /** Format: date-time */
      createdAt: string;
      /** @description The value itself. Shown at creation and unrecoverable afterwards. */
      key: string;
    };
    /** @enum {string} */
    ApiKeyKind: "publishable" | "secret";
    CreateApiKeyRequest: {
      /** @description How a Merchant tells one key from another when revoking. */
      name: string;
      kind: components["schemas"]["ApiKeyKind"];
    };
    ApiKeyList: {
      apiKeys: components["schemas"]["ApiKeySummary"][];
      /** @description Pass as `after` to fetch what follows this page. **Absent when there is no further page**, which is the only way to know the list has ended — a short page is not one. */
      nextCursor?: string;
    };
    ApiKeySummary: {
      /** Format: uuid */
      id: string;
      name: string;
      kind: components["schemas"]["ApiKeyKind"];
      /** Format: date-time */
      createdAt: string;
      /**
       * Format: date-time
       * @description When it stopped working, or `null` while it still does.
       */
      revokedAt: string | null;
    };
    ApiKeyNotFound: {
      /** @description What went wrong, in prose. */
      error: string;
      /**
       * @description Machine-readable. Branch on this.
       * @enum {string}
       */
      reason: "api-key-not-found";
    };
    ResolvedPrice: {
      variant: components["schemas"]["VariantIdentity"];
      price: {
        /** Format: uuid */
        id: string;
        amount: number;
        currency: string;
      };
      workflow: {
        name: string;
        steps: components["schemas"]["StepReport"][];
      };
    };
    VariantIdentity: {
      /** Format: uuid */
      id: string;
      sku: string;
    };
    StepReport: {
      /** @description The slot the Workflow declares. */
      step: string;
      /** @description The Step that filled it. Differs when a Project replaced it. */
      implementation: string;
    };
    ApiKeyRefusal: {
      error: string;
      /** @enum {string} */
      reason: "api-key-missing" | "api-key-malformed" | "api-key-unknown" | "api-key-revoked";
    };
    PriceRefusal: {
      error: string;
      /** @description Machine-readable. Branch on this. Core's own are `variant-not-found`, `price-not-set`; a Step this deployment supplied may refuse with anything else, which is answered 422 because Core cannot say what it means. */
      reason: string;
      workflow: {
        name: string;
        /** @description The slot that refused. */
        failed: string;
        steps: components["schemas"]["StepReport"][];
      };
    };
    Cart: {
      /**
       * Format: uuid
       * @description The identifier, and the whole of the authority to act on this Cart — there is no Shopper session to hang one off (ADR-0020). Treat it as a credential: it is unguessable, and anyone holding it can change this Cart.
       */
      id: string;
      shopper: components["schemas"]["CartShopper"];
      lineItems: components["schemas"]["CartLineItem"][];
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
      /**
       * Format: date-time
       * @description When this Cart stops being placeable. A lifetime fixed at creation, not an idle window — changing a Cart does not push it out.
       */
      expiresAt: string;
      /** @description Whether that moment has passed, as the server judges it. Branch on this rather than comparing `expiresAt` against a browser's clock. An expired Cart still reads and refuses every change. */
      expired: boolean;
      /** @description Whether this Cart has already become an Order. A Cart becomes exactly one, so this is final: a placed Cart still reads, and refuses every change and every further placement. Distinct from `expired` — an expired Cart ran out of time, and a placed one has already been bought. */
      placed: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CartLineItem: {
      /** Format: uuid */
      id: string;
      variant: components["schemas"]["VariantIdentity"];
      quantity: number;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata: {
        [key: string]: unknown;
      };
    };
    CartRefusal: {
      /** @description What went wrong, in prose. */
      error: string;
      /**
       * @description Machine-readable. Branch on this.
       * @enum {string}
       */
      reason: "invalid" | "malformed-body" | "secret-key-required" | "cart-not-found" | "cart-expired" | "cart-placed" | "line-item-not-found" | "variant-not-found" | "variant-not-priced";
    };
    CreateCartRequest: {
      /** @description Needs a secret key. A publishable one is refused (ADR-0020). */
      shopper?: ({
        email: string;
        externalId?: string | null;
      }) | null;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    UpdateCartRequest: {
      /** @description Needs a secret key. `null` detaches the Shopper; absent leaves whoever is on the Cart alone. */
      shopper?: ({
        email: string;
        externalId?: string | null;
      }) | null;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    AddCartLineItemRequest: {
      variantId: string;
      /** @description At least 1. Defaults to 1. */
      quantity?: number;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    UpdateCartLineItemRequest: {
      /** @description At least 1. Removing a line is `DELETE`, not a quantity of zero. */
      quantity?: number;
      /** @description Unindexed, untyped JSON owned by the Merchant and the Project. */
      metadata?: {
        [key: string]: unknown;
      };
    };
    PlacedOrder: components["schemas"]["Order"] & {
      workflow: {
        name: string;
        steps: components["schemas"]["StepReport"][];
      };
    };
    PlaceOrderRequestRefusal: {
      /** @description What went wrong, in prose. */
      error: string;
      /** @enum {string} */
      reason: "invalid" | "malformed-body" | "metadata-in-both";
    };
    PlaceOrderRefusal: {
      error: string;
      /** @description Machine-readable. Branch on this. Core's own are `cart-not-found`, `cart-expired`, `cart-placed`, `cart-empty`, `insufficient-inventory`, `variant-not-found`, `price-not-set`, `payment-declined`, `no-payment-provider`, `unknown-fulfilment-strategy`, `idempotency-key-reused`, `idempotency-key-in-progress`; a Step this deployment supplied may refuse with anything else, which is answered 422 because Core cannot say what it means. */
      reason: string;
      /** @description How far the Workflow got. Absent when the request was turned back before it ran at all — which is what an idempotency key already used for a different request, or one whose first attempt is still in flight, is refused by. Branch on `reason` rather than on this. */
      workflow?: {
        name: string;
        /** @description The slot that refused. */
        failed: string;
        steps: components["schemas"]["StepReport"][];
      };
    };
    SecretKeyRequired: {
      error: string;
      /** @enum {string} */
      reason: "secret-key-required";
    };
    PlaceOrderRequest: {
      /** @description The Cart to place. Holding its identifier is the whole of the authority to act on it (ADR-0020). */
      cartId: string;
      metadata?: components["schemas"]["OpenMetadata"];
    };
    /** @description Optional. The open half of the Workflow this request runs — whatever that deployment's Steps need and Core does not model: a card token for the Payment Provider, a lead time, a customer tier. It reaches every Step verbatim and is **never stored**; an entity's own `metadata` column is a different thing. Core reads no key out of it (ADR-0013). This request's query string reaches the same place and works the same way; send a key in only one of them, because a key in both is refused at 400 rather than resolved in favour of either. */
    OpenMetadata: {
      [key: string]: unknown;
    };
  };
  responses: never;
  parameters: {
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
